### ISSUE TITLE
Suggestion: Related discussions

### ISSUE THREAD

**Issue by sergiorodenas** [datlechin/flarum-more-discussions#7]
Hello! I think it could be nice to add "related" option and make use of search engine to get the results. What do you think? @datlechin

**Comment by datlechin** [comment]
You mean get the related discussions based on the search results by current discussion title?

**Comment by sergiorodenas** [comment]
Yeah, exactly

**Comment by sergiorodenas** [comment]
This makes even more sense as Algolia, Elasticsearch, TNT and Meilisearch can be used for searching by https://github.com/clarkwinkelmann/flarum-ext-scout

**Comment by datlechin** [comment]
Resolved in #10
